#_____INTERNAL CONFIG, DO NOT CHANGE______
#Node types
IGNORE = "ignore"
CONDITION = "condition"
LOOP = "loop"
PARSABLE = "parsable"
SPECIAL = "special"

NODE_CONTROL = "CONTROL"
NODE_FUSED = "FUSED"
NODE_COND_END_ANY = "END_"
NODE_COND_START = "COND_START"
NODE_COND_BRANCH = "COND_BRANCH"
NODE_COND_END = "COND_END"
NODE_SQL = "EXEC"
NODE_LABEL = "LABEL"
NODE_LOOP = "LOOP"